version: '3.1'
services:
  mongohost:
    image: mongo:7
    restart: always
    container_name: mongodb
    volumes:
      - mongohost_db:/data/db
    ports:
      - 27017:27017

  mongo_seed:
    image: mongo:7
    volumes:
      - ./seed_data:/seed_data
    command: bash -c "/seed_data/import.sh > /seed_data/import.log 2>&1 && exit 0"

    depends_on:
      - mongohost

  restapi:
    build: .
    restart: always
    container_name: restapi
    ports:
      - 5000:5137
    depends_on:
      - mongohost

volumes:
  mongohost_db:
